#!/usr/bin/env python3
"""Synchronize Gro Skills into a project without overwriting project knowledge.

Two modes per skill, declared in the project's `.gro-skills.json`:

  mirror   Whole directory is replaced verbatim from Gro Skills.
           For pure general-purpose discipline that needs no project detail.

  adapter  The project owns `SKILL.md` (a thin shell) and `references/template-*.md`.
           Only `references/common.md` (generated from the upstream SKILL.md) and
           other upstream resource files are overwritten.
           For skills that need project landing detail: doc paths, verification
           commands, stack conventions.

Usage:
  scripts/sync.py <project-root>
  scripts/sync.py <project-root> --check
  scripts/sync.py <project-root> --source /path/to/gro-skills/skills

Ported from vlog-app/tool/sync_gro_skills.dart. Changes from the original:
  - source resolved from this script's own location (was a hardcoded relative path)
  - mirror/adapter lists moved out of the code into `.gro-skills.json`
  - optional `.claude/skills -> ../.agents/skills` relative symlink
  - repo-root check is stack-agnostic (was Flutter-specific)
  - refuses to sync when the source repo has uncommitted changes, which would
    make sourceBlob (worktree) and sourceRevision (HEAD) disagree
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

CONFIG_NAME = ".gro-skills.json"
MANIFEST_NAME = ".gro-skills-sync.json"
SOURCE_ID = "gro-skills/skills"


def die(message: str) -> "NoReturn":  # type: ignore[valid-type]
    print(f"sync-gro-skills: {message}", file=sys.stderr)
    raise SystemExit(1)


# ---------------------------------------------------------------- git helpers

def git_hash(path: Path) -> str:
    result = subprocess.run(
        ["git", "hash-object", str(path)], capture_output=True, text=True
    )
    if result.returncode != 0:
        die(f"cannot hash {path}: {result.stderr.strip()}")
    return result.stdout.strip()


def git_revision(repo: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True
    )
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def git_is_dirty(repo: Path, subpath: str = "") -> list[str]:
    """Return the list of dirty paths under `subpath`, empty when clean."""
    args = ["git", "-C", str(repo), "status", "--porcelain"]
    if subpath:
        args += ["--", subpath]
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        return []
    return [line[3:] for line in result.stdout.splitlines() if line.strip()]


# ------------------------------------------------------------------ rendering

def strip_frontmatter(content: str) -> str:
    if not content.startswith("---\n"):
        return content
    end = content.find("\n---\n", 4)
    if end < 0:
        die("invalid SKILL.md frontmatter")
    return content[end + 5 :]


def render_common(skill: str, source_file: Path) -> str:
    body = strip_frontmatter(source_file.read_text(encoding="utf-8")).strip()
    return (
        f"<!-- Generated by scripts/sync.py; do not edit. "
        f"source={skill}/SKILL.md blob={git_hash(source_file)} -->\n\n{body}\n"
    )


def upstream_resources(source: Path) -> list[Path]:
    """Every upstream file except SKILL.md itself."""
    return sorted(
        p
        for p in source.rglob("*")
        if p.is_file() and not p.is_symlink() and p.relative_to(source).as_posix() != "SKILL.md"
    )


# --------------------------------------------------------------------- config

class Config:
    def __init__(self, project: Path, data: dict):
        self.mirror: list[str] = list(data.get("mirror", []))
        self.adapter: list[str] = list(data.get("adapter", []))
        self.destination: Path = project / data.get("destination", ".agents/skills")
        self.claude_link: bool = bool(data.get("claudeLink", True))
        overlap = set(self.mirror) & set(self.adapter)
        if overlap:
            die(f"skill listed in both mirror and adapter: {', '.join(sorted(overlap))}")
        if not self.mirror and not self.adapter:
            die(f"{CONFIG_NAME} declares no skills")

    @property
    def all_skills(self) -> list[str]:
        return self.mirror + self.adapter

    def mode(self, skill: str) -> str:
        return "mirror" if skill in self.mirror else "adapter"

    @staticmethod
    def load(project: Path) -> "Config":
        path = project / CONFIG_NAME
        if not path.exists():
            die(f"{path} not found — create it to declare mirror/adapter skills")
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            die(f"{path}: invalid json: {exc}")
        return Config(project, data)


# ------------------------------------------------------------------- syncing

def replace_directory(source: Path, destination: Path) -> None:
    if destination.is_symlink() or destination.is_file():
        destination.unlink()
    elif destination.is_dir():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, symlinks=False)


def sync_adapter(skill: str, source: Path, destination: Path) -> None:
    shell = destination / "SKILL.md"
    if not shell.exists():
        die(
            f"{skill}: project adapter SKILL.md missing; refusing to invent it. "
            f"Write a thin shell at {shell} that loads references/common.md."
        )
    common = destination / "references" / "common.md"
    common.parent.mkdir(parents=True, exist_ok=True)
    common.write_text(render_common(skill, source / "SKILL.md"), encoding="utf-8")
    for entry in upstream_resources(source):
        target = destination / entry.relative_to(source)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(entry, target)


def link_claude_dir(project: Path, destination: Path) -> str | None:
    """Create `.claude/skills -> ../.agents/skills` as a *relative* symlink.

    Relative so it survives being committed and cloned to another machine.
    Skipped when destination is not the conventional `.agents/skills`.
    """
    if destination != project / ".agents" / "skills":
        return None
    claude = project / ".claude"
    claude.mkdir(exist_ok=True)
    link = claude / "skills"
    target = "../.agents/skills"
    if link.is_symlink():
        if os.readlink(link) == target:
            return None
        link.unlink()
    elif link.exists():
        return f".claude/skills exists and is not a symlink — left untouched"
    link.symlink_to(target)
    return f"linked .claude/skills -> {target}"


# ------------------------------------------------------------------- checking

def snapshot(root: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        rel = path.relative_to(root).as_posix()
        if path.is_symlink():
            result[rel] = f"link:{os.readlink(path)}"
        elif path.is_dir():
            result[rel] = "dir"
        elif path.is_file():
            result[rel] = git_hash(path)
    return result


def check_mirror(skill: str, source: Path, destination: Path, failures: list[str]) -> None:
    if not destination.is_dir() or destination.is_symlink():
        failures.append(f"{skill}: destination missing or not a real directory")
        return
    src, dst = snapshot(source), snapshot(destination)
    for key in sorted(set(src) | set(dst)):
        if key not in src:
            failures.append(f"{skill}/{key}: extra destination entry")
        elif key not in dst:
            failures.append(f"{skill}/{key}: missing destination entry")
        elif src[key] != dst[key]:
            failures.append(f"{skill}/{key}: content differs")


def check_adapter(skill: str, source: Path, destination: Path, failures: list[str]) -> None:
    if not destination.is_dir() or destination.is_symlink():
        failures.append(f"{skill}: destination missing or not a real directory")
        return

    shell = destination / "SKILL.md"
    if not shell.exists():
        failures.append(f"{skill}/SKILL.md: project adapter missing")
    else:
        body = shell.read_text(encoding="utf-8")
        if "references/common.md" not in body:
            failures.append(f"{skill}/SKILL.md: common core is not explicitly loaded")
        # Project references are identified by exclusion, not by filename prefix:
        # anything under references/ that is neither the generated common core nor
        # an upstream resource. Naming varies by repo (template-*.md, <repo>-*.md).
        project_refs = project_references(destination, source)
        if not project_refs:
            failures.append(f"{skill}: project reference under references/ missing")
        for rel in project_refs:
            if rel not in body:
                failures.append(f"{skill}/SKILL.md: does not load {rel}")

    common = destination / "references" / "common.md"
    expected = render_common(skill, source / "SKILL.md")
    if not common.exists():
        failures.append(f"{skill}/references/common.md: missing")
    elif common.read_text(encoding="utf-8") != expected:
        failures.append(f"{skill}/references/common.md: upstream core differs")

    for entry in upstream_resources(source):
        rel = entry.relative_to(source).as_posix()
        target = destination / rel
        if not target.exists():
            failures.append(f"{skill}/{rel}: upstream resource missing")
        elif git_hash(entry) != git_hash(target):
            failures.append(f"{skill}/{rel}: upstream resource differs")


def check_manifest(cfg: Config, source: Path, failures: list[str]) -> None:
    path = cfg.destination / MANIFEST_NAME
    if not path.exists():
        failures.append(f"{MANIFEST_NAME}: manifest missing")
        return
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        failures.append(f"{MANIFEST_NAME}: invalid json: {exc}")
        return
    if data.get("source") != SOURCE_ID:
        failures.append(f"{MANIFEST_NAME}: source differs")
    if data.get("sourceRevision") != git_revision(source.parent):
        failures.append(f"{MANIFEST_NAME}: source revision differs")
    skills = data.get("skills")
    if not isinstance(skills, dict):
        failures.append(f"{MANIFEST_NAME}: skills missing")
        return
    for skill in cfg.all_skills:
        entry = skills.get(skill)
        if not isinstance(entry, dict):
            failures.append(f"{MANIFEST_NAME}: {skill} missing")
            continue
        if entry.get("mode") != cfg.mode(skill):
            failures.append(f"{MANIFEST_NAME}: {skill} mode differs")
        if entry.get("sourceBlob") != git_hash(source / skill / "SKILL.md"):
            failures.append(f"{MANIFEST_NAME}: {skill} source blob differs")


def write_manifest(cfg: Config, source: Path) -> None:
    skills: dict[str, dict] = {}
    for skill in cfg.all_skills:
        entry: dict = {
            "mode": cfg.mode(skill),
            "sourceBlob": git_hash(source / skill / "SKILL.md"),
        }
        if cfg.mode(skill) == "adapter":
            entry["projectReferences"] = project_references(
                cfg.destination / skill, source / skill
            )
        skills[skill] = entry
    payload = {
        "source": SOURCE_ID,
        "sourceRevision": git_revision(source.parent),
        "skills": skills,
        "note": (
            "Generated. Mirror files and adapter common cores are upstream-owned; "
            "adapter SKILL.md and template references are project-owned."
        ),
    }
    (cfg.destination / MANIFEST_NAME).write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def project_references(destination: Path, source: Path) -> list[str]:
    upstream = {p.relative_to(source).as_posix() for p in upstream_resources(source)}
    refs = destination / "references"
    if not refs.is_dir():
        return []
    out = []
    for path in sorted(refs.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(destination).as_posix()
        if rel == "references/common.md" or rel in upstream:
            continue
        out.append(rel)
    return out


# ----------------------------------------------------------------------- main

def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Gro Skills into a project.")
    parser.add_argument("project", help="project root")
    parser.add_argument("--check", action="store_true", help="verify without writing")
    parser.add_argument("--source", help="override the Gro Skills skills/ directory")
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        help="sync even if the source repo has uncommitted skill changes",
    )
    args = parser.parse_args()

    source = (
        Path(args.source).expanduser().resolve()
        if args.source
        else (Path(__file__).resolve().parent.parent / "skills")
    )
    if not source.is_dir():
        die(f"Gro Skills source not found: {source}")

    project = Path(args.project).expanduser().resolve()
    if not project.is_dir():
        die(f"project root not found: {project}")

    cfg = Config.load(project)

    # A dirty source makes sourceBlob (worktree) and sourceRevision (HEAD) disagree,
    # and risks propagating half-finished edits into every consuming project.
    dirty = git_is_dirty(source.parent, "skills")
    if dirty and not args.check and not args.allow_dirty:
        die(
            "source repo has uncommitted skill changes:\n  "
            + "\n  ".join(dirty)
            + "\nCommit them first, or pass --allow-dirty."
        )
    if dirty and args.check:
        print(f"sync-gro-skills: warning — source has {len(dirty)} uncommitted change(s)")

    failures: list[str] = []
    for skill in cfg.all_skills:
        src = source / skill
        if not (src / "SKILL.md").exists():
            failures.append(f"{skill}: source SKILL.md missing")

    if args.check:
        for skill in cfg.mirror:
            check_mirror(skill, source / skill, cfg.destination / skill, failures)
        for skill in cfg.adapter:
            check_adapter(skill, source / skill, cfg.destination / skill, failures)
        check_manifest(cfg, source, failures)
        if not failures:
            print("sync-gro-skills: in sync")
            return 0
        print(f"sync-gro-skills: {len(failures)} drift item(s):", file=sys.stderr)
        for item in failures:
            print(f"  - {item}", file=sys.stderr)
        return 1

    if failures:
        for item in failures:
            print(f"  - {item}", file=sys.stderr)
        return 1

    cfg.destination.mkdir(parents=True, exist_ok=True)
    for skill in cfg.mirror:
        replace_directory(source / skill, cfg.destination / skill)
        print(f"[ok] mirrored {skill}")
    for skill in cfg.adapter:
        sync_adapter(skill, source / skill, cfg.destination / skill)
        print(f"[ok] updated common core for {skill}")

    note = link_claude_dir(project, cfg.destination)
    if note:
        print(f"[ok] {note}")

    write_manifest(cfg, source)
    print(
        f"sync-gro-skills: synced {len(cfg.mirror)} mirror(s) "
        f"and {len(cfg.adapter)} adapter core(s)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
